name: "Build & Release"
on:
  workflow_dispatch:
    
  push:
    branches:
      - feature/*
      - develop
      - master
  pull_request:
    branches:
      - feature/*
      - develop
      - master

env:
  DOTNET_VERSION: '3.1.x'

jobs:
  Build-Release:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        source-url: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Build project 
      run: dotnet build --configuration Release

    - name: Run unit tests
      run: dotnet test --no-build --configuration Release

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pre_release_branches: develop,feature/*
        release_branches: master
        tag_prefix: ''

    - name: Pack
      run: dotnet pack -c Release -o ./nupkgs --no-build /p:Version=${{ steps.tag_version.outputs.new_tag }}
      
    - name: Publish
      run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${GITHUB_TOKEN} --skip-duplicate
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
    - name: Create a GitHub release (if master)
      if: github.ref == 'refs/heads/master'
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}